apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.deployment.namespace }}
  annotations:
    debug-info: "App secrets keys: {{ keys .Values.appSecrets | join \", \" }}"
type: Opaque
stringData:
  {{- if .Values.appSecrets }}
  {{- range $key, $value := .Values.appSecrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- else }}
  _debug_no_secrets: "No app secrets were provided"
  {{- end }}