apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.deployment.namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.appSecrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}