apiVersion: v1
kind: Secret
metadata:
  name: github-registry-secret
  namespace: {{ .Values.deployment.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }} 