apiVersion: v1
kind: Service
metadata:
  name: { { .Values.app.name } }
  namespace: { { .Values.deployment.namespace } }
spec:
  ports:
    - port: 80
      targetPort: { { .Values.deployment.exposedPort | default 80 } }
      protocol: TCP
      name: http
  selector:
    tier: { { .Values.app.tier | quote } }
    component: "app"
    app: { { .Values.app.name | quote } }
    env: { { .Values.deployment.environment | quote } }
