ARG RUNTIME_VERSION
ARG BUILD_PATH

FROM node:${RUNTIME_VERSION}-alpine
WORKDIR /app

RUN echo "PWD is: $PWD"
RUN ls

COPY ./build-artifact ./

RUN ls

CMD ["./node_modules/.bin/remix-serve", "dist/server/index.js"]
