ARG RUNTIME_VERSION
FROM nginx:${RUNTIME_VERSION}-alpine

ARG BUILD_PATH
ARG NGINX_CONF_PATH

COPY ${BUILD_PATH} /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ${NGINX_CONF_PATH} /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]