ARG RUNTIME_VERSION
ARG BUILD_PATH

FROM nginx:${RUNTIME_VERSION}-alpine

COPY ${BUILD_PATH} /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ${NGINX_CONF_PATH} /etc/nginx/conf.d

CMD ["nginx", "-g", "daemon off;"]