apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}
  namespace: argocd
spec:
  project: platform-apps
  source:
    repoURL: https://github.com/zinderlabs/.github
    targetRevision: HEAD
    path: helm/platform-app
  destination:
    server: https://kubernetes.default.svc
    namespace: ${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  helm:
    valueFiles:
      - values.yaml
