name: Build Yarn project

on:
  workflow_call:
    inputs:
      BUILD_COMMAND:
        required: true
        type: string
      NODE_VERSION:
        required: false
        type: string
        default: "18"
      BUILD_DIRECTORY:
        required: false
        type: string
        default: "dist"
      USE_LEGACY:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v4

      # - name: Enable corepack
      #   if: ${{ !inputs.USE_LEGACY }}
      #   run: corepack enable

      - name: Using Node version ${{ inputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: "yarn"

      - name: Use latest Yarn version # if legacy isn't used (image ships with 1.X.X)
        if: ${{ !inputs.USE_LEGACY }}
        run: yarn set version 4.1.1

      - name: Installing node dependencies
        run: yarn install --frozen-lockfile

      - name: Run Build Command
        run: yarn ${{ inputs.BUILD_COMMAND }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Payload
          path: ${{ inputs.BUILD_DIRECTORY }}
