name: Build .NET project

on:
  workflow_call:
    inputs:
      DOTNET_VERSION:
        required: false
        type: string
        default: "8.x"
      BUILD_COMMAND:
        required: false
        type: string
        default: publish -c Release
      BUILD_DIRECTORY:
        required: false
        type: string
        default: app/publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Setup dotnet ${{ inputs.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}
          cache: true

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet ${{ inputs.BUILD_COMMAND }} -o ${{ inputs.BUILD_DIRECTORY }}

      - name: Test with the dotnet CLI
        run: dotnet test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Payload
          path: ${{ inputs.BUILD_DIRECTORY }}
