name: Build NPM project

on:
  workflow_call:
    inputs:
      DEV_BUILD_COMMAND:
        required: false
        type: string
      PRD_BUILD_COMMAND:
        required: true
        type: string
      NODE_VERSION:
        required: false
        type: string
        default: "18"
      ENVIRONMENT:
        required: true
        type: string
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Using Node version ${{ inputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: "npm"
      - run: npm ci
      - name: Run Build Command
        run: |
          if [ "${{ inputs.ENVIRONMENT }}" == "prd" ]; then
            ${{ env.PRD_BUILD_COMMAND }} --if-present
          else
            ${{ env.DEV_BUILD_COMMAND }} --if-present
          fi
