name: Deploy Platform application with ArgoCD

on:
  workflow_call:

env:
  CONTAINER_REGISTRY: ghcr.io
  CI_ENVIRONMENT_SLUG: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev'}}
  PROJECT_NAME: ${{ github.event.repository.name }}-${{ github.ref == 'refs/heads/main' && 'prd' || 'dev'}}
  ENV_SECRETS: ${{ github.ref == 'refs/heads/main' && secrets.ENV_SECRETS_PRD || secrets.ENV_SECRETS_DEV }}
  APP_VALUES: ${{ github.ref == 'refs/heads/main' && 'values.prd.yaml' || 'values.dev.yaml' }}
  ARGOCD_SERVER: grafana.zinderlabs.com
  ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
  HELM_CHART_PATH: helm/platform-app
  HELM_VALUES_FILE: values.yaml
  KUBERNETES_DEST: https://kubernetes.default.svc

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Checkout repository workflow resources
        uses: actions/checkout@v4
        with:
          repository: zinderlabs/.github
          path: ci-central

      - name: Copy Helm charts to main repository
        run: |
          mkdir -p ${{ env.HELM_CHART_PATH }}
          cp -R ci-central/helm/platform-app/* ${{ env.HELM_CHART_PATH }}/

      - name: Create secret hash and source env variables
        run: |
          echo "${{env.ENV_SECRETS}}" | while IFS= read -r line || [[ -n "$line" ]]; do
            echo "$line" >> $GITHUB_ENV
          done
          echo "SECRET_HASH=$(echo -n "${{env.ENV_SECRETS}}" | sha512sum | awk '{print $1}')" >> $GITHUB_ENV
          echo "CI_PROJECT_NAME=${{ env.PROJECT_NAME }}" >> $GITHUB_ENV

      - name: Setup ArgoCD CLI
        uses: clowdhaus/argo-cd-action/@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: version
          options: |
            --client
            --grpc-web
            --loglevel debug 
            --logformat json

      - name: Configure ArgoCD CLI
        run: |
          argocd repo add ${{ github.server_url }}/${{ github.repository }}.git --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --upsert --grpc-web --loglevel debug --logformat json

      - name: Substitute variables in values.yaml
        run: |
          envsubst < ${{ github.workspace }}/${{ env.APP_VALUES }} > substituted_values.yaml
          cat substituted_values.yaml

      - name: Debug Helm templates
        run: |
          helm template ${{ env.HELM_CHART_PATH }} \
          --set deployment.pathSlug=${{ github.event.repository.name }} \
          --set deployment.image=${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}/${{ github.ref == 'refs/heads/main' && 'prd' || 'dev'}}:${{ github.ref == 'refs/heads/main' && 'main' || 'dev'}} \
          --set deployment.environment=${{ env.CI_ENVIRONMENT_SLUG }} \
          --set deployment.namespace=${{ env.PROJECT_NAME }} \
          --set secretHash=${{ env.SECRET_HASH }} \
          --values ${{ github.workspace }}/substituted_values.yaml \
          --debug

      - name: Apply ArgoCD Application
        run: |
          argocd app create ${{ env.PROJECT_NAME }} --upsert \
          --loglevel debug \
          --logformat json \
          --repo git@github.com:zinderlabs/.github.git \
          --path ${{ env.HELM_CHART_PATH }} \
          --dest-server ${{ env.KUBERNETES_DEST }} \
          --dest-namespace ${{ env.PROJECT_NAME }} \
          --revision main \
          --server ${{ env.ARGOCD_SERVER }} \
          --auth-token ${{ env.ARGOCD_AUTH_TOKEN }} \
          --grpc-web \
          --project ${{ github.event.repository.name }} \
          --helm-set deployment.pathSlug=${{ github.event.repository.name }} \
          --helm-set deployment.image=${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}/${{ github.ref == 'refs/heads/main' && 'prd' || 'dev'}}:${{ github.ref == 'refs/heads/main' && 'main' || 'dev'}} \
          --helm-set deployment.environment=${{ env.CI_ENVIRONMENT_SLUG }} \
          --helm-set deployment.namespace=${{ env.PROJECT_NAME }} \
          --helm-set secretHash=${{ env.SECRET_HASH }} \
          --values-literal-file ${{ github.workspace }}/substituted_values.yaml

      - name: Trigger ArgoCD sync
        uses: clowdhaus/argo-cd-action/@main
        with:
          command: app sync ${{ env.PROJECT_NAME }}
          options: |
            --server ${{ env.ARGOCD_SERVER }}
            --auth-token ${{ env.ARGOCD_AUTH_TOKEN }}
            --grpc-web
