name: Deploy Platform application to K8s

on:
  workflow_call:

env:
  CONTAINER_REGISTRY: ghcr.io
  HELM_VALUES: ${{ github.workspace }}/ci-central/workflow-resources/helm/platform/values.yaml
  PROJECT_NAME: ${{ github.repository.name }}-${{ github.ref == 'refs/heads/main' && 'prd' || 'dev'}}
  PROJECT_NAMESPACE: ${{ github.repository.name }}-${{ github.repository_id }}-${{ github.ref == 'refs/heads/main' && 'prd' || 'dev'}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository (which repository triggered this workflow)
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          path: main

      # Checkout the current repository (which we're currently in)
      - name: Checkout repository workflow resources
        uses: actions/checkout@v4
        with:
          repository: zinderlabs/.github
          path: ci-central

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Create secret in K8s for accessing the container registry
        run: |
          kubectl create namespace ${{ env.PROJECT_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret docker-registry github-registry \
              --namespace=${{ env.PROJECT_NAMESPACE }} \
              --docker-server=${{ env.CONTAINER_REGISTRY }} \
              --docker-username=${{ github.actor }} \
              --docker-password=${{ secrets.GITHUB_TOKEN }} \
              --dry-run=client -o yaml | kubectl apply -f -
          if ${{ github.ref == 'refs/heads/main' }} then
            kubectl create secret generic app-secret \
                --namespace=${{ env.PROJECT_NAMESPACE }} \
                --from-literal=APP_SECRET=${{ secrets.ENV_SECRETS_PRD }} \
                --dry-run=client -o yaml | kubectl apply -f -
            SECRET_HASH=$(echo -n $ENV_SECRET | sha512sum)
            set -o allexport; source $ENV_SECRET; set +o allexport
          else
            kubectl create secret generic app-secret \
                --namespace=${{ env.PROJECT_NAMESPACE }} \
                --from-literal=APP_SECRET=${{ secrets.ENV_SECRETS_DEV }} \
                --dry-run=client -o yaml | kubectl apply -f -
            SECRET_HASH=$(echo -n $ENV_SECRET | sha512sum)
            set -o allexport; source $ENV_SECRET; set +o allexport
          fi

      - name: Substitute environment variables in Helm values file
        uses: mshick/fast-envsubst@v1
        with:
          in-file: ${{ env.HELM_VALUES }}
          out-file: ${{ github.workspace }}/values-new.yaml

      - name: Debug check new helm values file
        run: |
          cat ${{ github.workspace }}/values-new.yaml || echo "No values file"

    #   - name: Deploy application using helm
    #     uses: WyriHaximus/github-action-helm3@v3
    #     with:
    #       #TODO
    #       exec: |
