name: Deploy Platform application with ArgoCD

on:
  workflow_call:

env:
  CONTAINER_REGISTRY: ghcr.io
  ENVIRONMENT_SLUG: ${{ github.ref == 'refs/heads/main' && 'prd' || 'staging'}}
  PROJECT_NAME: ${{ github.event.repository.name }}
  PROJECT_NAME_WITH_ENV: ${{ github.event.repository.name }}-${{ github.ref == 'refs/heads/main' && 'prd' || 'staging'}}
  ENV_SECRETS: ${{ github.ref == 'refs/heads/main' && secrets.ENV_SECRETS_PRD || secrets.ENV_SECRETS_DEV }}
  APP_VALUES: ${{ github.ref == 'refs/heads/main' && 'values.prd.yaml' || 'values.staging.yaml' }}
  ARGOCD_SERVER: argocd.zinderlabs.com
  ORG_ARGOCD_AUTH_TOKEN: ${{ secrets.ORG_ARGOCD_AUTH_TOKEN }}
  HELM_CHART_PATH: helm/platform-app
  KUBERNETES_DEST: https://kubernetes.default.svc
  MANIFEST_REPO: git@github.com:zinderlabs/.github.git
  ARGOCD_PROJECT: platform-apps
  SYNC_POLICY: ${{ github.ref == 'refs/heads/main' && 'none' || 'automated' }}

jobs:
  deploy:
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Checkout repository workflow resources
        uses: actions/checkout@v4
        with:
          repository: zinderlabs/.github
          path: ci-central

      - name: Copy Helm charts to main repository
        run: |
          mkdir -p ${{ env.HELM_CHART_PATH }}
          cp -R ci-central/helm/platform-app/* ${{ env.HELM_CHART_PATH }}/

      - name: Create secret hash
        env:
          ALL_SECRETS: ${{ toJSON(secrets) }}
          ALL_VARS: ${{ toJSON(vars) }}
        run: |
          MERGED_SECRETS=""
          if [ -n "$ALL_SECRETS" ]; then
            MERGED_SECRETS="$MERGED_SECRETS"$'\n'"$(echo "$ALL_SECRETS" | jq -r 'to_entries | map(select((.key | startswith("ORG_") | not) and (.key != "SSH_PRIVATE_KEY") and (.key != "github_token"))) | .[] | "\(.key)=\(.value)"')"
          fi
          if [ -n "$ALL_VARS" ]; then
            MERGED_SECRETS="$MERGED_SECRETS"$'\n'"$(echo "$ALL_VARS" | jq -r 'to_entries | map(select(.key | startswith("ORG_") | not)) | .[] | "\(.key)=\(.value)"')"
          fi

          if [ -n "$MERGED_SECRETS" ]; then
            SECRET_HASH=$(echo -n "$MERGED_SECRETS" | sha512sum | awk '{print $1}')
          else
            SECRET_HASH="nosecrets"
          fi
          echo "SECRET_HASH=$SECRET_HASH" >> $GITHUB_ENV
          echo "CI_PROJECT_NAME=${{ env.PROJECT_NAME }}" >> $GITHUB_ENV

      - name: Setup ArgoCD CLI
        uses: clowdhaus/argo-cd-action/@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: version
          options: |
            --client
            --grpc-web
            --loglevel debug
            --logformat json

      # - name: Configure ArgoCD CLI
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/argocd-key
      #     chmod 600 ~/.ssh/argocd-key
      #     argocd repo add git@github.com:${{ github.repository }}.git \
      #       --ssh-private-key-path ~/.ssh/argocd-key \
      #       --upsert \
      #       --grpc-web \
      #       --loglevel debug \
      #       --logformat json

      - name: Substitute variables in values.yaml
        run: |
          envsubst < ${{ github.workspace }}/${{ env.APP_VALUES }} > substituted_values.yaml
          cat substituted_values.yaml

      - name: Get project commit info
        id: project_commit
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repo_url=${{ github.server_url }}/${{ github.repository }}" >> $GITHUB_OUTPUT

      - name: Apply ArgoCD Application
        env:
          ALL_SECRETS: ${{ toJSON(secrets) }}
          ALL_VARS: ${{ toJSON(vars) }}
        run: |
          MERGED_SECRETS=""
          if [ -n "${{ env.ALL_SECRETS}}"]; then
            MERGED_SECRETS="$MERGED_SECRETS"$'\n'"$(echo "$ALL_SECRETS" | jq -r 'to_entries | map(select((.key | startswith("ORG_") | not) and (.key != "SSH_PRIVATE_KEY"))) and (.key != "github_token"))) | .[] | "\(.key)=\(.value)"')"
          fi
          if [ -n "${{ env.ALL_VARS }}"]; then
            MERGED_SECRETS="$MERGED_SECRETS"$'\n'"$(echo "$ALL_VARS" | jq -r 'to_entries | map(select(.key | startswith("ORG_") | not)) | .[] | "\(.key)=\(.value)"')"
          fi

          HELM_SET_ARGS=""
          while IFS='=' read -r key value; do
            HELM_SET_ARGS="$HELM_SET_ARGS --helm-set appSecrets.$key=$value"
          done <<< "$MERGED_SECRETS"

          argocd app create ${{ env.PROJECT_NAME_WITH_ENV }} --upsert \
          --loglevel debug \
          --logformat json \
          --repo ${{ env.MANIFEST_REPO }} \
          --path ${{ env.HELM_CHART_PATH }} \
          --dest-server ${{ env.KUBERNETES_DEST }} \
          --dest-namespace ${{ env.PROJECT_NAME_WITH_ENV }} \
          --revision main \
          --server ${{ env.ARGOCD_SERVER }} \
          --auth-token ${{ env.ORG_ARGOCD_AUTH_TOKEN }} \
          --grpc-web \
          --project ${{ env.ARGOCD_PROJECT }} \
          --helm-set imageCredentials.registry=${{ env.CONTAINER_REGISTRY }} \
          --helm-set imageCredentials.token=${{ secrets.ORG_CONTAINER_REGISTRY_TOKEN }} \
          --helm-set deployment.pathSlug=${{ github.event.repository.name }} \
          --helm-set deployment.image=${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}/${{ github.ref == 'refs/heads/main' && 'prd' || 'staging'}}:${{ github.ref == 'refs/heads/main' && 'main' || 'staging'}} \
          --helm-set deployment.environment=${{ env.ENVIRONMENT_SLUG }} \
          --helm-set deployment.namespace=${{ env.PROJECT_NAME_WITH_ENV }} \
          --helm-set deployment.projectCommit=${{ steps.project_commit.outputs.sha }} \
          --helm-set deployment.projectCommitShort=${{ steps.project_commit.outputs.short_sha }} \
          --helm-set deployment.projectRepoUrl=${{ steps.project_commit.outputs.repo_url }} \
          --helm-set secretHash=${{ env.SECRET_HASH }} \
          $HELM_SET_ARGS \
          --values-literal-file ${{ github.workspace }}/substituted_values.yaml \
          --sync-policy ${{ env.SYNC_POLICY }} \
          --sync-option CreateNamespace=true \
          --sync-option Force=true \
          --sync-option Replace=true
