name: Deploy Platform application with ArgoCD

on:
  workflow_call:

env:
  CONTAINER_REGISTRY: ghcr.io
  HELM_VALUES: ci-central/workflow-resources/helm/platform-app/values.yaml
  PROJECT_NAME: ${{ github.event.repository.name }}-${{ github.ref == 'refs/heads/main' && 'prd' || 'dev'}}
  ENV_SECRETS: ${{ github.ref == 'refs/heads/main' && secrets.ENV_SECRETS_PRD || secrets.ENV_SECRETS_DEV }}
  ARGOCD_SERVER: grafana.zinderlabs.com
  ARGOCD_CLI_BINARY: https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout repository workflow resources
        uses: actions/checkout@v4
        with:
          repository: zinderlabs/.github
          path: ci-central

      - name: Create secret hash and source env variables
        run: |
          for secret in $(echo -n "${{env.ENV_SECRETS}}"); do
            echo "${secret}" >> $GITHUB_ENV
          done
          echo "SECRET_HASH=$(echo -n "${{env.ENV_SECRETS}}" | sha512sum | awk '{print $1}')" >> $GITHUB_ENV

      - uses: clowdhaus/argo-cd-action/@main
        env:
          # Only required for first step in job where API is called
          # All subsequent setps in a job will not re-download the CLI
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: version
          options: --client

      # - name: Install ArgoCD CLI
      #   run: |
      #     curl -sSL -o argocd-linux-amd64 ${{ env.ARGOCD_CLI_BINARY }}
      #     sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
      #     rm argocd-linux-amd64

      # - name: Configure ArgoCD CLI
      #   run: |
      #     argocd config set server ${{ env.ARGOCD_SERVER }}
      #     argocd login set auth-token $ARGOCD_AUTH_TOKEN

      - name: Apply ArgoCD Application
        run: |
          CI_PROJECT_NAME=${{ github.event.repository.name }}
          CI_ENVIRONMENT_SLUG=${{ github.ref == 'refs/heads/main' && 'prd' || 'dev'}}
          GITHUB_REPO_URL=https://github.com/${{ github.repository }}

          envsubst < ci-central/argocd/application.yaml | argocd app create --upsert -f -

      - name: Trigger ArgoCD sync
        uses: clowdhaus/argo-cd-action/@main
        env:
          ARGOCD_AUTH_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJnaXRodWItYWN0aW9uOmFwaUtleSIsIm5iZiI6MTcyNjIyODI4MSwiaWF0IjoxNzI2MjI4MjgxLCJqdGkiOiI4ZjFhYzEyYi1iOTkyLTQzZTItYmMyZC03MWI3NGE3NzY2MDIifQ.UrbtRLPHUNleM9MmBC9OqsQ-QmbfqCiMeaOSP6O4oGs
        with:
          command: app sync ${{ github.event.repository.name }}
          options: |
            --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }}
            --server ${{ env.ARGOCD_SERVER }}
