name: Create Nginx Docker image

on:
  workflow_call:
    inputs:
      NGINX_VERSION:
        required: false
        type: string
        default: "1.26.2"
      BUILD_DIRECTORY:
        required: false
        type: string
        default: "dist"
      NGINX_CONFIG_PATH:
        required: false
        type: string
        default: "workflow-resources/docker/javascript/nginx.conf"

jobs:
  package-nginx:
    uses: ./.github/workflows/package-ci.yml
    with:
      RUNTIME_VERSION: ${{ inputs.NGINX_VERSION }}
      BUILD_DIRECTORY: ${{ inputs.BUILD_DIRECTORY }}
      DOCKERFILE_PATH: workflow-resources/docker/nginx/Dockerfile.nginx
      EXTRA_BUILD_ARGS: |
        NGINX_CONF_PATH=${{ inputs.NGINX_CONFIG_PATH }}
