name: Create .NET Docker image

on:
  workflow_call:
    inputs:
      DOTNET_VERSION:
        required: false
        type: string
        default: "8.x"
      BUILD_DIRECTORY:
        required: false
        type: string
        default: app/publish

jobs:
  package-java:
    uses: ./.github/workflows/package-ci.yml
    with:
      RUNTIME_VERSION: ${{ inputs.DOTNET_VERSION }}
      BUILD_DIRECTORY: ${{ inputs.BUILD_DIRECTORY }}
      DOCKERFILE_PATH: workflow-resources/docker/dotnet/Dockerfile
